(()=>{
'use strict';
const data=globalThis.GLOSSARY_DATA,quizData=globalThis.GLOSSARY_QUIZ_DATA,app=document.getElementById('app');
if(!data||!quizData||!app)return;
const APP_VERSION='3.0.0',STORAGE_KEY='riyoshi_glossary_learning_v1',TODAY_META_KEY='__today10',REVIEW_DATE='2026-07-17';
const states={safe:'安全',caution:'注意',danger:'危険'};
const intervals={danger:[0,1,3],caution:[1,3,7],safe:[7,14]};
let learning=loadLearning(),saveTimer=0,screen='home',listTerms=[],session=[],sessionIndex=0,revealed=false,assessedCurrent=false,sessionStats=null,todayQuizMode=false,isTodaySession=false,statusSessionMode=false,todayAnswers=new Map(),sessionId='',evaluatedIds=new Set(),flashcardMode=false,flashSwipeLocked=false,flashSuppressClickUntil=0;
function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function loadLearning(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch(_){return{}}}
function flushLearning(){if(saveTimer){clearTimeout(saveTimer);saveTimer=0}try{localStorage.setItem(STORAGE_KEY,JSON.stringify(learning))}catch(_){}}
function saveLearning(){if(saveTimer)return;saveTimer=setTimeout(flushLearning,40)}
addEventListener('pagehide',flushLearning);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushLearning()});
function stateKey(term){return `v136-${term.id}`}
function normalizeState(value={}){return{...value,history:Array.isArray(value.history)?value.history:[],recentAnswers:Array.isArray(value.recentAnswers)?value.recentAnswers.slice(-5):[],quizCorrect:Number(value.quizCorrect)||0,quizWrong:Number(value.quizWrong)||0,studyCount:Number(value.studyCount)||0,stage:Number(value.stage)||0}}
const normalizedKeys=new Set();
function termState(term){const key=stateKey(term);if(learning[key]){if(!normalizedKeys.has(key)){learning[key]=normalizeState(learning[key]);normalizedKeys.add(key)}return learning[key]}const old=learning[`v135-${term.id}`]||(term.legacyNumbers||[]).map(number=>learning[number]).find(Boolean);if(old){learning[key]=normalizeState(old);normalizedKeys.add(key);saveLearning();return learning[key]}return null}
function resultType(row){return row?.finalResult||row?.result||''}
function performanceFor(term){const rows=(termState(term)?.recentAnswers||[]).slice(-5),types=rows.map(resultType),first=types.filter(x=>x==='first_correct').length,rate=rows.length?Math.round(first/rows.length*100):null,lastTwo=types.slice(-2),twoBad=lastTwo.length===2&&lastTwo.every(x=>x==='wrong'||x==='unable');let level='none';if(twoBad)level='danger';else if(rows.length===0)level='none';else if(rows.length<5){if(types.some(x=>x==='wrong'||x==='unable'))level='caution';else if(types.every(x=>x==='first_correct'))level='safe';else level='caution'}else level=rate>=80?'safe':'caution';return{level,rows,rate,types}}
function finalPriority(term){const s=termState(term),self=s?.status||'',ability=performanceFor(term).level;if(!self&&ability==='none')return'unlearned';if(self==='danger'||ability==='danger')return'danger';if(self==='caution'||ability==='caution')return'caution';return'safe'}
let cachedToday='',cachedTodayAt=0;
function today(){const now=Date.now();if(cachedToday&&now-cachedTodayAt<60000)return cachedToday;const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now)),get=type=>parts.find(part=>part.type===type).value;cachedToday=`${get('year')}-${get('month')}-${get('day')}`;cachedTodayAt=now;return cachedToday}
function addDays(value,days){const [y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d+days,12));return date.toISOString().slice(0,10)}
function dateTime(){return new Date().toISOString()}
function emptyTodayMeta(){return{date:today(),dailyCounts:{},dailyTermIds:[],lastSession:{ids:[],results:{}},lastShown:{},countedSessionTerms:{},activeSession:null}}
function todayMeta(){const raw=learning[TODAY_META_KEY],base=emptyTodayMeta(),meta=raw&&typeof raw==='object'&&!Array.isArray(raw)?{...base,...raw}:base;if(meta.date!==today()){meta.date=today();meta.dailyCounts={};meta.dailyTermIds=[];meta.countedSessionTerms={}}meta.dailyCounts=meta.dailyCounts&&typeof meta.dailyCounts==='object'?meta.dailyCounts:{};meta.dailyTermIds=Array.isArray(meta.dailyTermIds)?meta.dailyTermIds:[];meta.countedSessionTerms=meta.countedSessionTerms&&typeof meta.countedSessionTerms==='object'?meta.countedSessionTerms:{};meta.lastSession=meta.lastSession&&typeof meta.lastSession==='object'?{ids:Array.isArray(meta.lastSession.ids)?meta.lastSession.ids:[],results:meta.lastSession.results&&typeof meta.lastSession.results==='object'?meta.lastSession.results:{}}:{ids:[],results:{}};meta.lastShown=meta.lastShown&&typeof meta.lastShown==='object'?meta.lastShown:{};learning[TODAY_META_KEY]=meta;return meta}
function saveTodayMeta(){todayMeta();saveLearning()}
function answerDay(row){return row?.answeredAt?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date(row.answeredAt)):''}

function isDue(term,includeToday=true){const value=termState(term)?.nextReviewDate;if(!value)return false;return includeToday?value<=today():value<today()}
function latestAnswer(term){const rows=termState(term)?.recentAnswers||[];return rows.length?rows[rows.length-1]:null}
function statusBucket(term){const s=termState(term),latest=latestAnswer(term);if(resultType(latest)==='unable')return'unable';return states[s?.status]?s.status:'unlearned'}
function stats(terms=data.terms){let safe=0,caution=0,danger=0,unable=0,due=0,correct=0,wrong=0,last='';for(const term of terms){const s=termState(term),bucket=statusBucket(term);if(bucket==='safe')safe++;else if(bucket==='caution')caution++;else if(bucket==='danger')danger++;else if(bucket==='unable')unable++;if(s&&isDue(term,false))due++;correct+=Number(s?.quizCorrect)||0;wrong+=Number(s?.quizWrong)||0;if(s?.lastStudyAt&&s.lastStudyAt>last)last=s.lastStudyAt}const learned=safe+caution+danger+unable,unlearned=terms.length-learned;return{total:terms.length,learned,unlearned,safe,caution,danger,unable,due,correct,wrong,rate:correct+wrong?Math.round(correct/(correct+wrong)*100):0,last}}
function statusSummary(terms){const s=stats(terms),pct=s.total?Math.round(s.learned/s.total*100):0,action=status=>`Glossary.startStatus('${status}')`;return `<section class="summary-card"><div class="ring" style="--progress:${pct}%"><span>${pct}%</span></div><div><div class="summary-label">学習進捗</div><div class="summary-main">${s.learned} / ${s.total}語</div><div class="summary-sub">学習済み ${s.learned}語　未学習 ${s.unlearned}語<br>確認問題正答率 ${s.correct+s.wrong?s.rate+'％':'未解答'}</div></div></section><section class="status-grid"><button type="button" class="status-box safe" onclick="${action('safe')}" aria-label="安全 ${s.safe}語を復習"><span class="status-dot"></span>安全<em>${s.safe}語</em></button><button type="button" class="status-box caution" onclick="${action('caution')}" aria-label="注意 ${s.caution}語を復習"><span class="status-dot"></span>注意<em>${s.caution}語</em></button><button type="button" class="status-box danger" onclick="${action('danger')}" aria-label="危険 ${s.danger}語を復習"><span class="status-dot"></span>危険<em>${s.danger}語</em></button><button type="button" class="status-box unable" onclick="${action('unable')}" aria-label="無理 ${s.unable}語を復習"><span class="status-bookmark" aria-hidden="true">🔖</span>無理<em>${s.unable}語</em></button></section><div class="progress-line"><i style="width:${pct}%"></i></div>`}
function summaryTerms(){return screen==='bookmark'?listTerms:data.terms}
function dateSortValue(value,fallback='9999-99-99'){return value||fallback}
function statusSort(status){return (a,b)=>{const sa=termState(a)||{},sb=termState(b)||{},lateA=sa.nextReviewDate&&sa.nextReviewDate<today()?0:1,lateB=sb.nextReviewDate&&sb.nextReviewDate<today()?0:1;if(status==='safe')return dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||dateSortValue(sa.lastStudyAt).localeCompare(dateSortValue(sb.lastStudyAt))||a.id-b.id;if(status==='unable'){const ua=latestAnswer(a)?.answeredAt||'9999-99-99',ub=latestAnswer(b)?.answeredAt||'9999-99-99';return lateA-lateB||ua.localeCompare(ub)||dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||a.id-b.id}return lateA-lateB||dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||dateSortValue(sa.lastStudyAt).localeCompare(dateSortValue(sb.lastStudyAt))||a.id-b.id}}
function categoryRoundRobin(terms){const groups=data.categories.map(category=>terms.filter(term=>term.category===category)),result=[];let added=true;while(added){added=false;for(const group of groups){if(group.length){result.push(group.shift());added=true}}}return result}
function showStatusMessage(message){document.querySelector('.status-message')?.remove();const box=document.createElement('div');box.className='status-message';box.setAttribute('role','status');box.innerHTML=`<span>${esc(message)}</span><button type="button" aria-label="閉じる">×</button>`;box.querySelector('button').addEventListener('click',()=>box.remove());app.appendChild(box);box.querySelector('button').focus()}
function startStatusFrom(source,status){const seen=new Set(),matching=source.filter(term=>{if(seen.has(term.id))return false;seen.add(term.id);return statusBucket(term)===status}),ordered=matching.sort(statusSort(status)),labels={safe:'安全の復習',caution:'注意の復習',danger:'危険の復習',unable:'無理の復習'},empty={safe:'安全に該当する用語はありません',caution:'注意に該当する用語はありません',danger:'危険に該当する用語はありません',unable:'無理に該当する用語はありません'};if(!ordered.length){showStatusMessage(empty[status]);return}startSession(ordered,labels[status],true,status)}
function startStatus(status){startStatusFrom(summaryTerms(),status)}
function formatDate(value){if(!value)return'―';const date=new Date(value.length===10?value+'T00:00:00+09:00':value);return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(date)}



function modeTerms(){return todayTerms()}
function priority(term){const s=termState(term),due=s?.nextReviewDate||'9999-99-99',late=due<today(),todayDue=due===today(),final=finalPriority(term),perf=performanceFor(term),lastRow=perf.rows.at(-1),last=resultType(lastRow);if(final==='danger'&&late)return 0;if(perf.rows.length>=2&&perf.rows.slice(-2).every(x=>['wrong','unable'].includes(resultType(x))))return 1;if(['wrong','unable'].includes(last)&&answerDay(lastRow)===addDays(today(),-1))return 2;if(final==='danger'&&todayDue)return 3;if(final==='caution'&&late)return 4;if(final==='caution'&&todayDue)return 5;if(final==='unlearned')return 6;if(final==='safe'&&todayDue)return 7;return 8}
function prioritySort(a,b){return priority(a)-priority(b)||(termState(a)?.nextReviewDate||'').localeCompare(termState(b)?.nextReviewDate||'')||a.id-b.id}
function dailySort(a,b){const sa=termState(a)||{},sb=termState(b)||{},meta=todayMeta();return priority(a)-priority(b)||dateSortValue(sa.nextReviewDate).localeCompare(dateSortValue(sb.nextReviewDate))||dateSortValue(sa.lastStudyAt).localeCompare(dateSortValue(sb.lastStudyAt))||dateSortValue(meta.lastShown[a.id],'0000-00-00').localeCompare(dateSortValue(meta.lastShown[b.id],'0000-00-00'))||(Number(sa.studyCount)||0)-(Number(sb.studyCount)||0)||a.id-b.id}
function dailyEligible(term){const meta=todayMeta(),s=termState(term)||{},last=resultType(latestAnswer(term));if((Number(meta.dailyCounts[term.id])||0)>=2)return false;if(['first_correct','second_correct'].includes(last)&&s.nextReviewDate&&s.nextReviewDate>today())return false;return true}
function diversifyToday(ordered,limit=Infinity){const result=[],left=[...ordered];while(left.length&&result.length<limit){const recent=result.slice(-2).map(row=>row.category),index=left.findIndex(term=>!recent.includes(term.category));result.push(left.splice(index<0?0:index,1)[0])}return result}
function todayTerms(){const meta=todayMeta(),previous=new Set(meta.lastSession.ids),previousResults=meta.lastSession.results,raw=[...new Map(data.terms.map(term=>[term.id,term])).values()].filter(dailyEligible).sort(dailySort),all=[];for(let level=0;level<=8;level++)all.push(...categoryRoundRobin(raw.filter(term=>priority(term)===level)));const picked=[];const add=term=>{if(picked.length<10&&!picked.some(row=>row.id===term.id))picked.push(term)};for(const term of all){if(priority(term)>6)continue;if(previous.has(term.id)&&!['wrong','unable'].includes(previousResults[term.id])&&priority(term)>3)continue;add(term)}for(const term of all){if(picked.length===10)break;if(priority(term)<=7&&!previous.has(term.id))add(term)}for(const release of ['', 'second_correct','first_correct']){if(picked.length===10)break;for(const term of all){if(picked.length===10)break;if((previousResults[term.id]||'')!==release)continue;if(termState(term)?.nextReviewDate>today())continue;add(term)}}return diversifyToday(picked)}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}

function syncFloatingNav(){const back=document.getElementById('glossaryBack');if(back)back.hidden=screen==='home'}

function renderHome(){screen='home';const bookmarkCount=data.terms.reduce((count,term)=>count+(isBookmarked(term)?1:0),0);app.innerHTML=`${statusSummary(data.terms)}<section class="home-feature-grid"><button class="home-feature-card feature-flash" type="button" onclick="Glossary.startMode('today')"><span class="home-feature-icon" aria-hidden="true">✓</span><span class="home-feature-copy"><strong>今日の10語</strong><small>3択クイズ（全10問）</small></span><span class="home-feature-arrow" aria-hidden="true">›</span></button><button class="home-feature-card feature-weak" type="button" onclick="Glossary.startFlashcards()"><span class="home-feature-icon" aria-hidden="true">▣</span><span class="home-feature-copy"><strong>用語カード</strong><small>664語をランダム学習</small></span><span class="home-feature-arrow" aria-hidden="true">›</span></button></section><button class="home-bookmark-card" type="button" onclick="Glossary.openBookmark()"><span aria-hidden="true">🔖</span><span><strong>ブックマーク</strong><small>${bookmarkCount}語</small></span><span class="home-feature-arrow" aria-hidden="true">›</span></button><section class="glossary-reset"><button onclick="Glossary.resetLearning()">用語の学習履歴をリセット</button></section><div class="app-version">Version ${APP_VERSION}</div>`;syncFloatingNav()}


function renderBookmark(){screen='bookmark';listTerms=data.terms.filter(term=>isBookmarked(term));app.innerHTML=`<section class="view-head"><span></span><h1>ブックマーク</h1><span></span></section>${statusSummary(listTerms)}<div id="list-container">${listCards(listTerms)}</div>`;syncFloatingNav()}
function listCards(terms){return terms.length?terms.map(term=>{const s=termState(term),due=isDue(term,false);return `<details class="term-card" id="term-${term.id}"><summary><span class="arrow">▶</span><span>${esc(term.name)}${due?'<br><span class="due-label">復習期限超過</span>':''}</span><span class="term-category">${esc(term.category)}</span></summary><div class="term-back">${termFields(term)}${sourceBlock(term)}<div class="assessment-inline">${assessmentButtons(term,s?.status,'inline')}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'未設定'}</div></div></details>`}).join(''):'<div class="empty">対象の用語はありません。</div>'}
function textField(label,value,extra=''){return value?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value">${esc(value)}</div></div>`:''}
function listField(label,values,extra=''){return values?.length?`<div class="term-field ${extra}"><div class="term-label">${esc(label)}</div><div class="term-value"><ul>${values.map(value=>`<li>${esc(value)}</li>`).join('')}</ul></div></div>`:''}
function termFields(term){return `${textField('定義',term.definition)}${term.aliases?.length?textField('別名・関連表記',term.aliases.join('／')):''}${Object.entries(term.special||{}).map(([label,value])=>textField(label,value)).join('')}${listField('試験の要点',term.exam,'exam-points')}${listField('混同注意',term.mixup)}`}
function flashcardFields(term){return `${textField('定義',term.definition)}${listField('試験の要点',term.exam,'exam-points')}${listField('混同注意',term.mixup)}`}
function sourceBlock(term){const links=(term.sources||[]).map(source=>source.url?`<a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.label)}</a>`:esc(source.label)).join('<br>');return `<details class="source-details"><summary>出典・監修状態</summary><div class="source-content">${esc(term.sourceText)}${links?`<br>${links}`:''}<br><span class="review-pill">${esc(term.status)}</span>　基準日：${REVIEW_DATE}</div></details>`}

function assessmentButtons(term,current,kind='session'){return Object.entries(states).map(([key,label])=>`<button class="${key}${current===key?' selected':''}" onclick="Glossary.assess(${term.id},'${key}','${kind}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}
function startMode(mode){if(mode!=='today')return;const terms=modeTerms(),label=terms.length===10?'今日の10語':`今日の${terms.length}語`;if(!terms.length){showStatusMessage('今日の学習対象はありません');return}startSession(terms,label,false,'','today')}
function beginTodayTracking(){const meta=todayMeta(),key=id=>`${sessionId}:${id}`;meta.lastSession={ids:session.map(term=>term.id),results:Object.fromEntries(session.map(term=>[term.id,'']))};for(const term of session){const unique=key(term.id);if(meta.countedSessionTerms[unique])continue;meta.countedSessionTerms[unique]=true;meta.dailyCounts[term.id]=(Number(meta.dailyCounts[term.id])||0)+1;meta.dailyTermIds.push(term.id);meta.lastShown[term.id]=today()}meta.activeSession={sessionId,ids:session.map(term=>term.id),index:0,label:sessionStats.label,answers:{},stats:sessionStats,evaluatedIds:[]};saveTodayMeta()}
function persistTodaySession(){if(!isTodaySession)return;const meta=todayMeta();meta.activeSession={sessionId,ids:session.map(term=>term.id),index:sessionIndex,label:sessionStats.label,answers:Object.fromEntries(todayAnswers),stats:sessionStats,evaluatedIds:[...evaluatedIds]};for(const [id,response] of todayAnswers)meta.lastSession.results[id]=response.finalResult||'';saveTodayMeta()}
function startSession(terms,label='用語学習',useThreeChoice=false,sourceStatus='',modeKey=''){if(!terms.length){showStatusMessage('対象の用語はありません');return}screen='session';flashcardMode=false;session=[...terms];sessionIndex=0;sessionId=`gs-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;statusSessionMode=Boolean(sourceStatus);isTodaySession=modeKey==='today';todayQuizMode=isTodaySession||useThreeChoice;todayAnswers=new Map();evaluatedIds=new Set();sessionStats={label,sourceStatus,studied:0,correct:0,firstCorrect:0,secondCorrect:0,wrong:0,unable:0,safe:0,caution:0,danger:0};if(isTodaySession)beginTodayTracking();prepareTerm();renderSession()}
function startFlashcards(){screen='session';flashcardMode=true;session=shuffle([...data.terms]);sessionIndex=0;sessionId=`fc-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;statusSessionMode=false;isTodaySession=false;todayQuizMode=false;todayAnswers=new Map();evaluatedIds=new Set();sessionStats={label:'用語カード',sourceStatus:'',studied:0,correct:0,firstCorrect:0,secondCorrect:0,wrong:0,unable:0,safe:0,caution:0,danger:0};prepareTerm();renderSession()}
function toggleFlashcard(){if(!flashcardMode)return;revealed=!revealed;renderSession()}
function flashNext(){if(!flashcardMode||flashSwipeLocked)return;flashSwipeLocked=true;if(sessionIndex<session.length-1){sessionIndex++}else{const last=currentTerm()?.id;const nextDeck=shuffle([...data.terms]);if(nextDeck.length>1&&nextDeck[0].id===last)[nextDeck[0],nextDeck[1]]=[nextDeck[1],nextDeck[0]];session.push(...nextDeck);sessionIndex++}prepareTerm();renderSession();scrollTo(0,0);setTimeout(()=>{flashSwipeLocked=false},180)}
function flashPrevious(){if(!flashcardMode||flashSwipeLocked||sessionIndex<=0)return;flashSwipeLocked=true;sessionIndex--;prepareTerm();renderSession();scrollTo(0,0);setTimeout(()=>{flashSwipeLocked=false},180)}
function bindFlashGestures(){const card=document.querySelector('.flash-card');if(!card)return;let startX=0,startY=0,tracking=false;card.addEventListener('touchstart',event=>{if(event.touches.length!==1||flashSwipeLocked)return;const touch=event.touches[0];startX=touch.clientX;startY=touch.clientY;tracking=true},{passive:true});card.addEventListener('touchcancel',()=>{tracking=false},{passive:true});card.addEventListener('touchend',event=>{if(!tracking||flashSwipeLocked)return;tracking=false;const touch=event.changedTouches[0];if(!touch)return;const dx=touch.clientX-startX,dy=touch.clientY-startY,ax=Math.abs(dx),ay=Math.abs(dy);if(ax<55||ax<=ay*1.25)return;event.preventDefault();flashSuppressClickUntil=Date.now()+500;if(dx<0)flashNext();else flashPrevious()},{passive:false});card.addEventListener('click',event=>{if(Date.now()<flashSuppressClickUntil){event.preventDefault();return}toggleFlashcard()})}
function isBookmarked(term){return Boolean(termState(term)?.bookmarked)}
function toggleBookmark(id){const term=data.terms.find(row=>row.id===id);if(!term)return;const key=stateKey(term),old=termState(term)||{};learning[key]={...old,bookmarked:!old.bookmarked};saveLearning();if(screen==='session')renderSession();else if(screen==='bookmark')renderBookmark();else renderHome()}
function assessFlash(id,status){const term=data.terms.find(row=>row.id===id);if(!term||!states[status])return;setStatus(term,status);renderSession()}
function prepareTerm(){revealed=false;assessedCurrent=false}
function currentTerm(){return session[sessionIndex]}
function renderSession(){const term=currentTerm(),s=termState(term),progress=Math.round(sessionIndex/session.length*100);if(flashcardMode){const cycleCount=data.terms.length,cyclePosition=sessionIndex%cycleCount+1,flashProgress=Math.round(cyclePosition/cycleCount*100);app.innerHTML=`<div class="study-progress"><i style="width:${flashProgress}%"></i></div><section class="study-card flash-study-card"><button type="button" class="flash-card ${revealed?'is-back':''}" aria-label="カードを裏返す">${revealed?`<div class="flash-back"><div class="term-category">${esc(term.category)}</div>${flashcardFields(term)}</div>`:`<div class="flash-front"><div class="term-category">${esc(term.category)}</div><div class="flash-term-main"><div><h2>${esc(term.name)}</h2><div class="term-reading">${esc(term.reading||'')}</div></div></div></div>`}</button><div class="flash-actions"><button type="button" onclick="Glossary.toggleBookmark(${term.id})">${isBookmarked(term)?'🔖 ブックマーク済み':'🔖 ブックマーク'}</button></div><div class="assessment">${Object.entries(states).map(([key,label])=>`<button class="${key}${s?.status===key?' selected':''}" onclick="Glossary.assessFlash(${term.id},'${key}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}</div><div class="session-navigation"><button onclick="Glossary.flashPrevious()" ${sessionIndex===0?'disabled':''}>戻る</button><button class="session-next" onclick="Glossary.flashNext()">次へ</button></div></section><div class="flash-count-bottom">${cyclePosition} / ${cycleCount}語</div>`;syncFloatingNav();bindFlashGestures();return}app.innerHTML=`<section class="view-head"><span></span><h1>${esc(sessionStats.label)}</h1><span></span></section><div class="study-count">${sessionIndex+1} / ${session.length}語</div><div class="study-progress"><i style="width:${progress}%"></i></div><section class="study-card"><div class="term-front"><div><div class="term-category">${esc(term.category)}</div><h2>${esc(term.name)}</h2></div></div>${todayQuizHtml(term)}</section>`;syncFloatingNav()}
function todayResponse(term=currentTerm()){if(todayAnswers.has(term.id))return todayAnswers.get(term.id);const question=quizData.questions?.[term.id],distractors=question?shuffle([...question.distractors]).slice(0,2):[],options=question?shuffle([{text:question.correct,correct:true},...distractors.map(text=>({text,correct:false}))]):[],response={question:question?.question||'',source:question?.source||'',options,hold:!question,attempts:[],completed:false,autoStatus:'',currentStatus:'',counted:false,originalResult:'',finalResult:'',unable:false,unableTiming:'',recorded:false};todayAnswers.set(term.id,response);persistTodaySession();return response}
function performanceHtml(term,response){const perf=performanceFor(term),s=termState(term),symbols={first_correct:'○',second_correct:'△',wrong:'×',unable:'🔖'},label={safe:'安全候補',caution:'注意',danger:'危険',none:'データなし'}[perf.level],final={safe:'安全相当',caution:'注意相当',danger:'危険相当',unlearned:'未学習'}[finalPriority(term)],notice=response.unable?'自力回答不能として記録されています':s?.status==='safe'&&['caution','danger'].includes(perf.level)?'実績では要注意':['caution','danger'].includes(s?.status)&&perf.level==='safe'?'実績は改善傾向です':'';return `<details class="performance-details"><summary>正答実績</summary><div>自己評価：${states[s?.status]||'未設定'}<br>実力評価：${label}<br>直近5回：${perf.rows.map(x=>symbols[resultType(x)]||'').join(' ')||'記録なし'}<br>1回目正解率：${perf.rate===null?'未算出':perf.rate+'％'}<br>復習優先度：${final}<br>次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'未設定'}${notice?`<br><span class="performance-notice">${notice}</span>`:''}</div></details>`}
function todayQuizHtml(term){const response=todayResponse(term),wrong=new Set(response.attempts.filter(index=>!response.options[index].correct));return `<section class="quiz today-quiz"><h3>${esc(response.question)}</h3>${response.options.map((option,index)=>`<button class="quiz-choice ${wrong.has(index)?'wrong ':''}${response.completed&&option.correct?'correct ':''}" onclick="Glossary.chooseToday(${index})" ${(response.completed||wrong.has(index))?'disabled':''}>${index+1}．${esc(option.text)}</button>`).join('')}<button class="unable-button" aria-label="自力で回答できない" onclick="Glossary.markUnable()" ${response.unable?'disabled':''}>🔖 無理</button>${response.attempts.length===1&&!response.completed?'<div class="quiz-result retry">不正解です。残りの選択肢から、もう一度選んでください。</div>':''}${response.completed?`<div class="quiz-result">${response.unable?'自力で回答できなかったものとして記録しました。':response.autoStatus==='safe'?'1回目で正解です。':response.autoStatus==='caution'?'2回目で正解です。':'正解を確認してください。'}</div><div class="term-back">${termFields(term)}${sourceBlock(term)}</div>${todayAssessmentArea(term,response)}${performanceHtml(term,response)}`:''}</section>${sessionNavigation()}`}
function finalResultFor(response){if(response.unable)return'unable';const last=response.attempts.at(-1),correct=response.options[last]?.correct;if(correct)return response.attempts.length===1?'first_correct':'second_correct';return response.attempts.length>=2?'wrong':''}
function saveRecentAnswer(term,response){const key=stateKey(term),s=termState(term)||{},result=finalResultFor(response);if(!result)return;const rows=[...(s.recentAnswers||[])],existing=rows.findIndex(x=>x.sessionId===sessionId&&x.termId===term.id),row={id:`${sessionId}-${term.id}`,sessionId,termId:term.id,answeredAt:dateTime(),mode:sessionStats.label,firstChoice:response.attempts[0]??null,secondChoice:response.attempts[1]??null,originalResult:response.originalResult||result,finalResult:result,unable:response.unable,unableTiming:response.unableTiming||'',automaticStatus:response.autoStatus,manualStatus:response.currentStatus||response.autoStatus,reason:response.unable?'利用者が自力回答不能を申告':''};if(existing>=0)rows[existing]={...rows[existing],...row};else rows.push(row);learning[key]={...s,recentAnswers:rows.slice(-5)};saveLearning();response.recorded=true}
function applyQuizOutcome(term,response){const previous=response.finalResult||'',next=finalResultFor(response);if(!next||previous===next)return;if(previous){if(previous==='first_correct')sessionStats.firstCorrect--;else if(previous==='second_correct')sessionStats.secondCorrect--;else if(previous==='wrong')sessionStats.wrong--;else if(previous==='unable')sessionStats.unable--;adjustQuizTotals(term,previous,-1)}if(next==='first_correct')sessionStats.firstCorrect++;else if(next==='second_correct')sessionStats.secondCorrect++;else if(next==='wrong')sessionStats.wrong++;else sessionStats.unable++;adjustQuizTotals(term,next,1);response.finalResult=next;saveRecentAnswer(term,response);persistTodaySession()}
function adjustQuizTotals(term,result,delta){const key=stateKey(term),s=termState(term)||{},correct=result==='first_correct'||result==='second_correct';learning[key]={...s,quizCorrect:Math.max(0,(Number(s.quizCorrect)||0)+(correct?delta:0)),quizWrong:Math.max(0,(Number(s.quizWrong)||0)+(correct?0:delta))};saveLearning()}
function chooseToday(index){const term=currentTerm(),response=todayResponse(term);if(response.completed||response.attempts.includes(index))return;response.attempts.push(index);const correct=response.options[index].correct;if(correct||response.attempts.length===2){response.completed=true;response.originalResult=correct?(response.attempts.length===1?'first_correct':'second_correct'):'wrong';response.autoStatus=correct?(response.attempts.length===1?'safe':'caution'):'danger';response.currentStatus=response.autoStatus;applyQuizOutcome(term,response);setStatus(term,response.autoStatus,true,`3択:${response.originalResult}`);sessionStats[response.autoStatus]++;evaluatedIds.add(term.id)}renderSession()}
function markUnable(){const term=currentTerm(),response=todayResponse(term);if(response.unable)return;response.unable=true;response.unableTiming=response.completed?'after':'before';if(!response.completed){response.completed=true;response.originalResult='unable'}response.autoStatus='danger';if(response.currentStatus&&sessionStats[response.currentStatus]>0)sessionStats[response.currentStatus]--;response.currentStatus='danger';sessionStats.danger++;applyQuizOutcome(term,response);setStatus(term,'danger',true,'利用者が自力回答不能を申告');evaluatedIds.add(term.id);renderSession()}
function todayAssessmentArea(term,response){const s=termState(term);return `<div class="assessment">${Object.entries(states).map(([key,label])=>`<button class="${key}${response.currentStatus===key?' selected':''}" onclick="Glossary.overrideToday('${key}')">${key==='safe'?'🟢':key==='caution'?'🟡':'🔴'} ${label}</button>`).join('')}</div><div class="next-review">次回復習日：${s?.nextReviewDate?formatDate(s.nextReviewDate):'自己評価後に設定'}</div>`}
function overrideToday(status){const term=currentTerm(),response=todayResponse(term);if(!response.completed||!states[status])return;if(response.currentStatus!==status){sessionStats[response.currentStatus]=Math.max(0,sessionStats[response.currentStatus]-1);sessionStats[status]++;response.currentStatus=status;setStatus(term,status,false,'手動自己評価を優先');saveRecentAnswer(term,response);persistTodaySession()}renderSession()}


function sessionNavigation(){return `<div class="session-navigation"><button onclick="Glossary.previousTerm()">前の用語</button><button class="session-next" onclick="Glossary.nextTerm()">${sessionIndex===session.length-1?'結果を見る':'次へ'}</button></div>`}




function setStatus(term,status,automatic=false,reason=''){const key=stateKey(term),old=termState(term)||{},now=dateTime(),previous=old.status||'',same=previous===status,ability=performanceFor(term).level,rank={danger:1,caution:2,safe:3},effective=rank[ability]&&rank[ability]<rank[status]?ability:status,stage=same?Math.min((Number(old.stage)||0)+1,intervals[effective].length-1):0;let days=intervals[effective][stage];if(automatic&&reason==='3択:second_correct'&&effective==='caution')days=3;learning[key]={...old,status,performanceLevel:ability,reviewPriority:effective,previousStudyAt:old.lastStudyAt||null,lastStudyAt:now,nextReviewDate:addDays(today(),days),stage,studyCount:(Number(old.studyCount)||0)+1,improved:previous?rank[status]>rank[previous]:false,history:[...(Array.isArray(old.history)?old.history:[]),{at:now,status,automatic,performanceLevel:ability,reviewPriority:effective,reason}].slice(-50)};saveLearning();return learning[key]}
function assess(id,status,kind){const term=data.terms.find(row=>row.id===id);if(!term)return;if(screen==='session'&&assessedCurrent)return;setStatus(term,status);if(screen==='session'){sessionStats[status]++;assessedCurrent=true;evaluatedIds.add(term.id);renderSession()}else if(screen==='bookmark'){renderBookmark()}else renderHome()}
function nextTerm(){if(todayQuizMode){const response=todayResponse();if(response.completed&&!response.counted){sessionStats.studied++;response.counted=true;saveRecentAnswer(currentTerm(),response)}}else sessionStats.studied++;if(sessionIndex<session.length-1){sessionIndex++;persistTodaySession();prepareTerm();renderSession();scrollTo(0,0)}else renderResult()}
function previousTerm(){if(sessionIndex>0){sessionIndex--;persistTodaySession();prepareTerm();renderSession();scrollTo(0,0)}else{if(isTodaySession){todayMeta().activeSession=null;saveTodayMeta()}renderHome()}}
function renderResult(){screen='result';if(isTodaySession){const meta=todayMeta();meta.activeSession=null;saveTodayMeta()}const unanswered=Math.max(0,session.length-sessionStats.studied),final={safe:0,caution:0,danger:0};for(const term of session){if(!evaluatedIds.has(term.id))continue;const status=termState(term)?.status;if(final[status]!==undefined)final[status]++}app.innerHTML=`<section class="view-head"><span></span><h1>学習結果</h1><span></span></section><section class="result-card"><h2>${esc(sessionStats.label)}</h2><div class="result-grid"><div>学習した用語<br>${sessionStats.studied}語</div><div>自力で正解<br>${sessionStats.firstCorrect}問</div><div>2回目で正解<br>${sessionStats.secondCorrect}問</div><div>不正解<br>${sessionStats.wrong}問</div><div>🔖 無理<br>${sessionStats.unable}問</div><div>未回答<br>${unanswered}語</div><div>最終評価：安全<br>${final.safe}語</div><div>最終評価：注意<br>${final.caution}語</div><div>最終評価：危険<br>${final.danger}語</div></div><div class="result-actions"><button class="next-button next-ten-button" onclick="Glossary.nextTodaySet()">次の10語へ</button><button class="next-button return-glossary-button" onclick="Glossary.home()">ホームへ戻る</button></div></section>`;syncFloatingNav()}

function nextTodaySet(){const meta=todayMeta();meta.activeSession=null;saveTodayMeta();startMode('today')}
function resetLearning(){if(!confirm('用語集の安全・注意・危険、解答履歴、復習予定をすべて削除します。この操作は元に戻せません。'))return;learning={};try{localStorage.removeItem(STORAGE_KEY)}catch(_){}normalizedKeys.clear();renderHome()}


function restoreActiveToday(){const active=todayMeta().activeSession;if(!active||!Array.isArray(active.ids)||!active.ids.length||!active.sessionId)return false;const terms=active.ids.map(id=>data.terms.find(term=>term.id===Number(id))).filter(Boolean);if(!terms.length)return false;screen='session';session=terms;sessionIndex=Math.min(Math.max(0,Number(active.index)||0),terms.length-1);sessionId=active.sessionId;statusSessionMode=false;isTodaySession=true;todayQuizMode=true;todayAnswers=new Map(Object.entries(active.answers||{}).map(([id,response])=>[Number(id),response]));evaluatedIds=new Set((active.evaluatedIds||[]).map(Number));sessionStats={label:active.label||`今日の${terms.length}語`,sourceStatus:'',studied:0,correct:0,firstCorrect:0,secondCorrect:0,wrong:0,unable:0,safe:0,caution:0,danger:0,...(active.stats||{})};prepareTerm();renderSession();return true}
function exitCurrent(){if(isTodaySession){todayMeta().activeSession=null;saveTodayMeta()}renderHome()}
globalThis.Glossary={home:renderHome,startFlashcards,toggleFlashcard,flashNext,flashPrevious,toggleBookmark,assessFlash,openBookmark:renderBookmark,back(){if(screen!=='home')exitCurrent()},startMode,startStatus,chooseToday,markUnable,overrideToday,assess,nextTerm,previousTerm,resetLearning,nextTodaySet,exitSession:exitCurrent};
renderHome();
})();
